#!/usr/local/bin/node


var opts = require('tav').set({
    collection: {
        note: 'Remote Tiddler Collection URI',
        value: null
    }
}, "wikify some tiddlywiki text");


// require the jsdom and jquery libraries, via NODE_PATH
// (probably /usr/local/lib/node if you are using npm)
var jsdom = require('jsdom');
var jquery = require('jquery');
var fs = require('fs');
var http = require('http')
var url = require('url');
var window = jsdom.jsdom(
        '<html><head></head><body><div id="tiddler"></div></body></html>'
    ).createWindow(); 

// jquery-ize the window
var jQuery = jquery.create(window);
var createWikifier = require('./twikifier.js').createWikifier;


var formatText = function(wikify, text) {
    // create a browser window
    var place = window.document.getElementById('tiddler');;

    // wikify the tiddler text.
    // XXX This should be functional, returning a string,
    // not building up the dom in place.
    wikify(text, place, null, null);

    return window.document.innerHTML;
}

var run = function(wikify, file) {
    var text = '';

    file.on('data', function(chunk) {
        text += chunk;
    });

    file.on('end', function() {
        console.log(formatText(wikify, text));
    });
};

// read a file to get text
var runFile = function(wikify, filename) {
    var text = '';
    stream = fs.createReadStream(filename, { 'encoding': 'utf8' });
    run(wikify, stream);
}

// read stdin to get text
var runStdin = function(wikify) {
    var stdin = process.openStdin();
    stdin.setEncoding('utf8');
    run(wikify, stdin);
}

var loadRemoteTiddlers = function(store, Tiddler, jsonTiddlers) {
    var tiddlers = JSON.parse(jsonTiddlers);
    for (var i = 0; i < tiddlers.length ; i++) {
        var t = new Tiddler(tiddlers[i].title);
        t.text = tiddlers[i].text;
        t.tags = tiddlers[i].tags;
        t.modifier = tiddlers[i].modifier;
        t.modified = Date.convertFromYYYYMMDDHHMM(tiddlers[i].modified)
        t.created = Date.convertFromYYYYMMDDHHMM(tiddlers[i].created)
        t.fields = tiddlers[i].fields;
        store.addTiddler(t);
    }
}

var processdata = function(wikify) {
    var arglength = opts.args.length;
    if (arglength) {
        for (var i = 0; i < arglength ; i++) {
            runFile(wikify, opts.args[i]);
        }
    } else {
        runStdin(wikify);
    }
}

var main = function() {
    // Create formatter for the window.
    var globals = createWikifier(window, jQuery);
    var wikify = globals[0];
    var store = globals[1];
    var Tiddler = globals[2];

    var uri = opts.collection
    if (uri) {
        var parsed_uri = url.parse(uri);

        var client = http.createClient(parsed_uri.port ? parsed_uri.port : 80,
            parsed_uri.hostname);
        var request = client.request('GET', parsed_uri.pathname + '?fat=1', 
            {'host': parsed_uri.hostname,
             'accept': 'application/json'});
        request.end();
        request.on('response', function(response) {
            response.setEncoding('utf8');
            var data = ''
            response.on('data', function(chunk) {
                data += chunk;
            });
            response.on('end', function() {
                loadRemoteTiddlers(store, Tiddler, data);
                processdata(wikify);
            });
        });
    } else {
        processdata(wikify);
    }
}

exports.formatText = formatText;

if (module.parent === null)
    main();
