#!/bin/sh

USER=tiddlyweb
NODE_PATH=/usr/local/lib/node
DAEMON=/home/cdent/src/twikifier/server.js
NODE_BIN=/usr/local/bin/node

set -e

sudo -u $USER $NODE_BIN $DAEMON | logger -p syslog.info -t twikifier
